# SPDX-License-Identifier: GPL-2.0-or-later
# Based on OpenOrbis's public hello_world Makefile, not the proprietary SDK.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(SO_PLATFORM_ORBIS ON CACHE BOOL "OpenOrbis target" FORCE)
set(OO_PS4_TOOLCHAIN "$ENV{OO_PS4_TOOLCHAIN}" CACHE PATH "Installed OpenOrbis SDK")
if(NOT OO_PS4_TOOLCHAIN)
    message(FATAL_ERROR "Set OO_PS4_TOOLCHAIN to a complete OpenOrbis SDK")
endif()
foreach(required include/stdio.h lib/crt1.o link.x)
    if(NOT EXISTS "${OO_PS4_TOOLCHAIN}/${required}")
        message(FATAL_ERROR "Incomplete OpenOrbis SDK: missing ${required}")
    endif()
endforeach()
find_program(CMAKE_C_COMPILER NAMES clang REQUIRED NO_CMAKE_FIND_ROOT_PATH)
find_program(CMAKE_CXX_COMPILER NAMES clang++ REQUIRED NO_CMAKE_FIND_ROOT_PATH)
find_program(CMAKE_AR NAMES llvm-ar REQUIRED NO_CMAKE_FIND_ROOT_PATH)
find_program(CMAKE_RANLIB NAMES llvm-ranlib REQUIRED NO_CMAKE_FIND_ROOT_PATH)
find_program(SO_LLD NAMES ld.lld REQUIRED NO_CMAKE_FIND_ROOT_PATH)
set(CMAKE_C_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(CMAKE_SYSROOT "${OO_PS4_TOOLCHAIN}")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_FLAGS_INIT "-fPIC -funwind-tables -march=btver2 -isystem \"${OO_PS4_TOOLCHAIN}/include\"")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -nostdinc++ -isystem \"${OO_PS4_TOOLCHAIN}/include/c++/v1\"")
# Link with LLD directly, so a desktop CRT or libstdc++ cannot leak into the ELF.
set(_SO_LINK "\"${SO_LLD}\" -m elf_x86_64 -pie --script \"${OO_PS4_TOOLCHAIN}/link.x\" --eh-frame-hdr <LINK_FLAGS> <OBJECTS> \"${OO_PS4_TOOLCHAIN}/lib/crt1.o\" -o <TARGET> -L\"${OO_PS4_TOOLCHAIN}/lib\" --start-group <LINK_LIBRARIES> -lc -lkernel")
set(CMAKE_C_LINK_EXECUTABLE "${_SO_LINK} --end-group")
set(CMAKE_CXX_LINK_EXECUTABLE "${_SO_LINK} -lc++ --end-group")
set(CMAKE_FIND_ROOT_PATH "${OO_PS4_TOOLCHAIN}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
